import Head from 'next/head'
import '@styles/tailwind.css';
import { ProviderAuth } from '@hooks/use-auth';

function MyApp({ Component, pageProps }) {
  return(
    <ProviderAuth>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Component {...pageProps} />
      </main>
    </ProviderAuth>
  );
}

export default MyApp
